# Generated by Django 6.0 on 2026-02-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('members', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
            ],
        ),
    ]
